module.exports = [
  {
    id: 1003,
    //nextId: 1008,
    isQuestion: true,
    componentName: 'MultiplierQuestion',
    playTitle: 'Patriots Receive the Ball',
    choices: [
      { id: 0, value: 'Out/Bounds', nextId: 0 },
      { id: 1, value: 'Touchback', nextId: 0 },
      { id: 2, value: 'Return', nextId: 0 },
    ],
    correctAnswer: 'Touchback',
    forTeam: { id: 2, teamName: 'Patriots' },
    title: 'Receives',
    shortHand: 'Receives',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 3,
    inProgressLength: 3,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    //hideTimeout: true,
    type: 'LivePlay',
    multiplier: 1,
  },
  {
    id: 1008,
    //nextId: 1012,
    isQuestion: true,
    componentName: 'GameMasterQuestion',
    playTitle: 'What will the next play be?',
    choices: [
      { id: 0, value: 'Run', nextId: 0 },
      { id: 1, value: 'Pass', nextId: 0 },
    ],
    correctAnswer: 'Pass',
    forTeam: {},
    title: 'GameMaster',
    shortHand: 'GameMaster',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [{ sequence: 1, value: 'Play Card  - Action lasts 5 sec.' }],
    length: 0,
    specialTimer: 27,
    isMultiplier: false,
    backgroundColor: '#19d1bf',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    ringImage: 'symbol-gm_white.svg',
    //showResult: true,
    //hideTimeout: true,
    stars: 0,
    type: 'GameMaster',
  },
  {
    id: 2002,
    //nextId: 2003,
    isQuestion: true,
    componentName: 'SponsorQuestion',
    playTitle: 'Will the JAGS score this possession?',
    choices: [
      { id: 0, value: 'No', nextId: 0 },
      { id: 1, value: 'Yes', nextId: 0 },
    ],
    correctAnswer: 'Yes',
    forTeam: {},
    title: 'Sponsor Play',
    shortHand: 'Sponsor Play',
    choiceType: 'MULTI',
    points: 5000,
    tokens: 50,
    answer: 1,
    labels: [],
    length: 0,
    specialTimer: 27,
    isMultiplier: false,
    backgroundColor: '#495bdb',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    ringImage: 'symbol-sponsor_white.svg',
    showResult: true,
    stars: 1,
    type: 'Sponsor',
  },
  {
    id: 1016,
    // nextId: 1017,
    isQuestion: true,
    componentName: 'AdvertisementQuestion',
    playTitle: 'Will Tom Brady be intercepted this series?',
    choices: [
      { id: 0, value: 'No', nextId: 0 },
      { id: 1, value: 'Yes', nextId: 0 },
    ],
    correctAnswer: 'No',
    forTeam: {},
    title: 'Prize Play',
    shortHand: 'Prize Play',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [{ sequence: 1, value: 'Play Card  - Action lasts 5 sec.' }],
    length: 3,
    specialTimer: 27,
    isMultiplier: false,
    backgroundColor: '#9368AA',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    ringImage: 'symbol-prize_white.svg',
    prizeImage: 'prize-icon-coffee.jpg',
    prizeDesc: 'Free Coffee',
    prizeDetailDesc: 'Prize Play',
    prizePoints: 0,
    //showResult: true,
    //hideTimeout: true,
    stars: 1,
    type: 'Prize',
  },

  //-- LIVEGAME 2X --------------------------------------------------------------------------------------------------------------------
  {
    id: 1012,
    //nextId: 1015,
    isQuestion: true,
    componentName: 'MultiplierQuestion',
    playTitle: 'Run, Pass or Turnover 2X',
    choices: [
      { id: 0, value: 'Run', nextId: 1013 },
      { id: 1, value: 'Pass', nextId: 1013 },
    ],
    correctAnswer: 'Pass',
    forTeam: { id: 2, teamName: 'Patriots' },
    title: '',
    shortHand: '2X',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 8,
    inProgressLength: 6,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    isTextCard: true,
    //hideTimeout: true,
    type: 'LivePlay',
    multiplier: 2,
  },
  {
    id: 1013,
    nextId: 0,
    isQuestion: true,
    componentName: 'MultiplierQuestion',
    playTitle: 'Loss, No Gain, Gain',
    choices: [
      { id: 0, value: 'Loss', nextId: 0 },
      { id: 1, value: 'No Gain', nextId: 0 },
      { id: 2, value: 'Gain', nextId: 0 },
    ],
    correctAnswer: 'Gain',
    forTeam: { id: 2, teamName: 'Patriots' },
    title: '',
    shortHand: '',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 9,
    inProgressLength: 8,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    isTextCard: true,
    //hideTimeout: true,
    type: 'LivePlay',
  },

  //--LIVEGAME 3X ------------------------------------------------------------------------------------------------------------------
  {
    id: 10033,
    //nextId: 1008,
    isQuestion: true,
    componentName: 'MultiplierQuestion',
    playTitle: 'Patriots Receive the Ball 3X',
    choices: [
      { id: 0, value: 'Out/Bounds', nextId: 1004 },
      { id: 1, value: 'Touch Back', nextId: 1005 },
      { id: 2, value: 'Return', nextId: 1006 },
    ],
    correctAnswer: 'Touch Back',
    forTeam: { id: 2, teamName: 'Patriots' },
    title: 'Receives',
    shortHand: '3X',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 3,
    inProgressLength: 3,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    type: 'LivePlay',
    multiplier: 3,
  },
  {
    id: 1004,
    nextId: 0,
    isQuestion: true,
    componentName: 'MultiplierQuestion',
    playTitle: 'The ball',
    choices: [
      { id: 0, value: 'kick ob', nextId: 0 },
      { id: 1, value: 'roll ob', nextId: 0 },
    ],
    correctAnswer: 'kick ob',
    forTeam: { id: 2, teamName: 'Patriots' },
    title: '',
    shortHand: 'The Ball',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 8,
    inProgressLength: 1,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    type: 'LivePlay',
  },
  {
    id: 1005,
    nextId: 0,
    isQuestion: true,
    componentName: 'MultiplierQuestion',
    playTitle: 'How - TB',
    choices: [
      { id: 0, value: 'kneel', nextId: 0 },
      { id: 1, value: 'end zone', nextId: 0 },
    ],
    correctAnswer: 'end zone',
    forTeam: { id: 2, teamName: 'Patriots' },
    title: '',
    shortHand: 'How - TB',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 8,
    inProgressLength: 1,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    type: 'LivePlay',
  },
  {
    id: 1006,
    nextId: 0,
    isQuestion: true,
    componentName: 'MultiplierQuestion',
    playTitle: 'Loss, No Gain or Gain?',
    choices: [
      { id: 0, value: 'Loss', nextId: 0 },
      { id: 1, value: 'No Gain', nextId: 0 },
      { id: 2, value: 'Gain', nextId: 1007 },
    ],
    correctAnswer: 'Loss',
    forTeam: { id: 2, teamName: 'Patriots' },
    title: '',
    shortHand: '',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 8,
    inProgressLength: 1,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    type: 'LivePlay',
  },
  {
    id: 1007,
    nextId: 0,
    isQuestion: true,
    componentName: 'MultiplierQuestion',
    playTitle: '# of Yards ?',
    choices: [
      { id: 0, value: '0-5', nextId: 0 },
      { id: 1, value: '5-15', nextId: 0 },
      { id: 2, value: '15-25', nextId: 0 },
      { id: 3, value: '25-35', nextId: 0 },
      { id: 4, value: '+35', nextId: 0 },
    ],
    correctAnswer: 'No Gain',
    forTeam: { id: 2, teamName: 'Patriots' },
    title: '',
    shortHand: '',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 8,
    inProgressLength: 1,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    type: 'LivePlay',
  },
  //--------------------------------------------------------------------------------------------------------------------
  {
    id: 9999,
    nextId: 0,
    componentName: 'Summary',
    title: 'Summary',
    shortHand: 'Summary',
    type: 'Summary',
  },
]
