module.exports = [
  {
    componentName: 'GetReady',
    length: 20,
  },
  {
    componentName: 'ExplainationScreen',
    length: 4,
  },
  {
    sequence: 10,
    componentName: 'MultiplierQuestion',
    type: `Live Play`,
    playTitle: `Patriots Receive the Ball`,
    component: `3-Sided (A-B-C)`,
    choices: [
      { id: 0, value: "'Out/Bounds'" },
      { id: 1, value: "'Touch Back'" },
      { id: 2, value: "'Return'" },
    ],
    forTeam: { id: 1, teamName: `Patriots` },
    title: `Receives`,
    shortHand: `Receives`,
    choiceType: 'MULTI',
    points: 50,
    tokens: 20,
    answer: `Touch Back`,
    labels: [{ sequence: 1, value: null }],
    length: 8,
    specialTimer: 13,
    note: `LOCKOUT - 3 sec.         before the kick`,
  },
  {
    sequence: 11,
    componentName: 'MultiplierQuestion',
    type: `Multiplier 2X`,
    playTitle: `Loss, No Gain or Gain?`,
    component: `3-Sided (A-B-C)`,
    choices: [
      { id: 0, value: "'Loss'" },
      { id: 1, value: "'No Gain'" },
      { id: 2, value: "'Gain'" },
    ],
    forTeam: { id: 1, teamName: `Patriots` },
    title: null,
    shortHand: null,
    choiceType: 'MULTI',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: null }],
    length: 8,
    specialTimer: 13,
    note: null,
  },
  {
    sequence: 12,
    componentName: 'MultiplierQuestion',
    type: `Multiplier 2X - TB`,
    playTitle: `How - TB`,
    component: `A-B`,
    choices: ['Kneel', 'End Zone'],
    forTeam: { id: 1, teamName: `Patriots` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: `End Zone`,
    labels: [{ sequence: 1, value: null }],
    length: 8,
    specialTimer: 13,
    note: null,
  },
  {
    sequence: 13,
    componentName: 'MultiplierQuestion',
    type: `Multiplier 2X - OB`,
    playTitle: `The Ball`,
    component: `A-B`,
    choices: ['Kick OB', 'Rolls OB'],
    forTeam: { id: 1, teamName: `Patriots` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: null }],
    length: 8,
    specialTimer: 13,
    note: null,
  },
  {
    sequence: 14,
    componentName: 'MultiplierQuestion',
    type: `Multiplier 3X`,
    playTitle: `# of Yards ?`,
    component: `Yard Selector`,
    choices: [
      { id: 0, value: "'0-3'" },
      { id: 1, value: "'4-10'" },
      { id: 2, value: "'11-15'" },
      { id: 3, value: "'16-25'" },
      { id: 4, value: "'26-35'" },
      { id: 5, value: "'+35'" },
    ],
    forTeam: { id: 1, teamName: `Patriots` },
    title: null,
    shortHand: null,
    choiceType: 'MULTI',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: null }],
    length: 8,
    specialTimer: 13,
    note: `LOCKOUT - 3 sec.         before the kick`,
  },
  {
    sequence: 15,
    componentName: 'MultiplierQuestion',
    type: `Play in Progress + Results`,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: `Play In Process` }],
    length: 8,
    specialTimer: 13,
    note: null,
  },
  {
    sequence: 16,
    componentName: 'MultiplierQuestion',
    type: `Play Begins and Ends`,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: `Touch Back`,
    labels: [{ sequence: 1, value: `Play Card - Action lasts 4 sec.` }],
    length: 4,
    specialTimer: 20,
    note: null,
  },
  {
    sequence: 17,
    componentName: 'MultiplierQuestion',
    type: `1ST & 10 AT NE 25         LIVE PLAY `,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: `Touch Back               1st and 10 on the 25`,
    labels: [{ sequence: 1, value: `RESULTS  - lasts 2 sec. ` }],
    length: 2,
    specialTimer: 22,
    note: null,
  },
  {
    sequence: 18,
    componentName: 'MultiplierQuestion',
    type: `GameMaster - Host`,
    playTitle: `What will the next play be?`,
    component: `A-B`,
    choices: ['Run - Pass'],
    forTeam: { id: 1, teamName: `Patriots` },
    title: `GameMaster`,
    shortHand: `GameMaster`,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: `Pass`,
    labels: [{ sequence: 1, value: `Play Card  - Action lasts 5 sec.` }],
    length: 5,
    specialTimer: 27,
    note: null,
  },
  {
    sequence: 19,
    componentName: 'MultiplierQuestion',
    type: `Play Begins and Ends`,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: `Play Card  - Action lasts 6sec.`,
    shortHand: `Play Card  - Action lasts 6sec.`,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: `TIME OUT -  lasts 2 sec. ` }],
    length: 2,
    specialTimer: 29,
    note: `TIME OUT -  lasts 2sec. `,
  },
  {
    sequence: 20,
    componentName: 'MultiplierQuestion',
    type: `LIVE PLAY`,
    playTitle: `Loss, No Gain or Gain?`,
    component: `3-Sided (A-B-C)`,
    choices: [
      { id: 0, value: "'Loss'" },
      { id: 1, value: "'No Gain'" },
      { id: 2, value: "'Gain'" },
    ],
    forTeam: { id: 1, teamName: `Patriots` },
    title: `Live Play`,
    shortHand: `Live Play`,
    choiceType: 'MULTI',
    points: 50,
    tokens: 20,
    answer: `Gain`,
    labels: [{ sequence: 1, value: null }],
    length: 11,
    specialTimer: 40,
    note: null,
  },
  {
    sequence: 21,
    componentName: 'MultiplierQuestion',
    type: `Multiplier 2X - Gain`,
    playTitle: `# of Yards ?`,
    component: `Yard Selector`,
    choices: [
      { id: 0, value: "'0-3'" },
      { id: 1, value: "'4-10'" },
      { id: 2, value: "'11-15'" },
      { id: 3, value: "'16-25'" },
      { id: 4, value: "'26-35'" },
      { id: 5, value: "'+35'" },
    ],
    forTeam: { id: 1, teamName: `Patriots` },
    title: null,
    shortHand: null,
    choiceType: 'MULTI',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: `LOCKOUT -  3 sec. before the hike` }],
    length: 11,
    specialTimer: 40,
    note: `LOCKOUT - in 3 sec.         before the hike`,
  },
  {
    sequence: 22,
    componentName: 'MultiplierQuestion',
    type: `Play in Progress + Results`,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: `Play In Process` }],
    length: 8,
    specialTimer: 51,
    note: null,
  },
  {
    sequence: 23,
    componentName: 'MultiplierQuestion',
    type: `Play Begins and Ends`,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: `GAIN - 5 yards `,
    labels: [{ sequence: 1, value: `Play Card - Action lasts 8 sec.` }],
    length: 10,
    specialTimer: 53,
    note: null,
  },
  {
    sequence: 24,
    componentName: 'MultiplierQuestion',
    type: `2ND & 5 AT NE 30        LIVE PLAY `,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: `Gain - 5 Yds            2nd Down`,
    labels: [{ sequence: 1, value: `RESULTS  - lasts 2 sec. ` }],
    length: 53,
    specialTimer: 106,
    note: null,
  },
  {
    sequence: 25,
    componentName: 'MultiplierQuestion',
    type: `LIVE PLAY`,
    playTitle: `Pass, Run or Turnover`,
    component: `3-Sided (A-B-C)`,
    choices: [
      { id: 0, value: "'Run'" },
      { id: 1, value: "'Pass'" },
      { id: 2, value: "'or Turnover'" },
    ],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: `Live Play`,
    shortHand: `Live Play`,
    choiceType: 'MULTI',
    points: 50,
    tokens: 20,
    answer: `Pass`,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 26,
    componentName: 'MultiplierQuestion',
    type: `Multiplier 2X`,
    playTitle: `Loss, No Gain, Gain`,
    component: null,
    choices: [
      { id: 0, value: "'Loss'" },
      { id: 1, value: "'No Gain'" },
      { id: 2, value: "'Gain'" },
    ],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'MULTI',
    points: 50,
    tokens: 20,
    answer: `Gain`,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 27,
    componentName: 'MultiplierQuestion',
    type: `Multiplier 3X`,
    playTitle: `# of Yards ?`,
    component: `Yard Selector`,
    choices: [
      { id: 0, value: "'0-3'" },
      { id: 1, value: "'4-10'" },
      { id: 2, value: "'11-15'" },
      { id: 3, value: "'16-25'" },
      { id: 4, value: "'26-35'" },
      { id: 5, value: "'+35'" },
    ],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'MULTI',
    points: 50,
    tokens: 20,
    answer: `Gain - 31 yards `,
    labels: [{ sequence: 1, value: `LOCKOUT -  3 sec. before the hike` }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 28,
    componentName: 'MultiplierQuestion',
    type: `Play in Progress + Results`,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: `Play In Process` }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 29,
    componentName: 'MultiplierQuestion',
    type: `Play Begins and Ends`,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: `Gain 31 yards - 40 Yd line 1st and 10`,
    labels: [{ sequence: 1, value: `RESULTS  - lasts 2 sec. ` }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 30,
    componentName: 'MultiplierQuestion',
    type: `4TH & 1 AT JAX 30        LIVE PLAY `,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: `Play Card - Action lasts 8 sec.` }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 31,
    componentName: 'MultiplierQuestion',
    type: `LIVE PLAY`,
    playTitle: `Loss, No Gain or Gain?`,
    component: `3-Sided`,
    choices: [
      { id: 0, value: "'Loss'" },
      { id: 1, value: "'No Gain'" },
      { id: 2, value: "'Gain'" },
    ],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: `Live Play`,
    shortHand: `Live Play`,
    choiceType: 'MULTI',
    points: 50,
    tokens: 20,
    answer: `No Gain`,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 32,
    componentName: 'MultiplierQuestion',
    type: `Prize Play`,
    playTitle: `Will the Patriots J.Brady
be intercepted this series?`,
    component: `A-B`,
    choices: ['No', 'Yes'],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: `Prize Play`,
    shortHand: `Prize Play`,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: `No`,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 33,
    componentName: 'MultiplierQuestion',
    type: `Play in Progress + Results`,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 34,
    componentName: 'MultiplierQuestion',
    type: `Play Begins and Ends`,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: `No Gain - Time Out`,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 35,
    componentName: 'MultiplierQuestion',
    type: `4TH & 1 AT JAX 30        LIVE PLAY `,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 36,
    componentName: 'MultiplierQuestion',
    type: `LIVE PLAY`,
    playTitle: `Pass, Run or Turnover`,
    component: `3-Sided`,
    choices: [
      { id: 0, value: "'Run'" },
      { id: 1, value: "'Pass'" },
      { id: 2, value: "'or Turnover'" },
    ],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: `Live Play`,
    shortHand: `Live Play`,
    choiceType: 'MULTI',
    points: 50,
    tokens: 20,
    answer: `Pass`,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 37,
    componentName: 'MultiplierQuestion',
    type: `Multiplier 2X`,
    playTitle: `Loss, No Gain or Gain?`,
    component: `3-Sided`,
    choices: [
      { id: 0, value: "'Loss'" },
      { id: 1, value: "'No Gain'" },
      { id: 2, value: "'Gain'" },
    ],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'MULTI',
    points: 50,
    tokens: 20,
    answer: `Gain`,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 38,
    componentName: 'MultiplierQuestion',
    type: `Play in Progress + Results`,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 39,
    componentName: 'MultiplierQuestion',
    type: `Play Begins and Ends`,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: `1st & 10`,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 40,
    componentName: 'MultiplierQuestion',
    type: `4TH & 13 AT JAX 13        LIVE PLAY `,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 41,
    componentName: 'MultiplierQuestion',
    type: `LIVE PLAY`,
    playTitle: `Will the field goal attempt hit the upright?`,
    component: `A-B`,
    choices: ['No', 'Yes'],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: `Live Play`,
    shortHand: `Live Play`,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: `No`,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 42,
    componentName: 'MultiplierQuestion',
    type: `Play Begins and Ends`,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: `END QUARTER 1`,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 43,
    componentName: 'MultiplierQuestion',
    type: null,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 44,
    componentName: 'MultiplierQuestion',
    type: `1ST & 10 AT NE 28        LIVE PLAY `,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 45,
    componentName: 'MultiplierQuestion',
    type: `LIVE PLAY`,
    playTitle: `Pass, Run or Turnover`,
    component: `3-Sided`,
    choices: [
      { id: 0, value: "'Run'" },
      { id: 1, value: "'Pass'" },
      { id: 2, value: "'or Turnover'" },
    ],
    forTeam: { id: 1, teamName: `Patriots` },
    title: `Live Play`,
    shortHand: `Live Play`,
    choiceType: 'MULTI',
    points: 50,
    tokens: 20,
    answer: `Pass`,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 46,
    componentName: 'MultiplierQuestion',
    type: `Multiplier 2X`,
    playTitle: `Loss, No Gain, Gain`,
    component: null,
    choices: [
      { id: 0, value: "'Loss'" },
      { id: 1, value: "'No Gain'" },
      { id: 2, value: "'Gain'" },
    ],
    forTeam: { id: 1, teamName: `Patriots` },
    title: null,
    shortHand: null,
    choiceType: 'MULTI',
    points: 50,
    tokens: 20,
    answer: `Gain`,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 47,
    componentName: 'MultiplierQuestion',
    type: `Multiplier 3X`,
    playTitle: `# of Yards ?`,
    component: `Yard Selector`,
    choices: [
      { id: 0, value: "'0-3'" },
      { id: 1, value: "'4-10'" },
      { id: 2, value: "'11-15'" },
      { id: 3, value: "'16-25'" },
      { id: 4, value: "'26-35'" },
      { id: 5, value: "'+35'" },
    ],
    forTeam: { id: 1, teamName: `Patriots` },
    title: null,
    shortHand: null,
    choiceType: 'MULTI',
    points: 50,
    tokens: 20,
    answer: `24 yards Gain`,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 48,
    componentName: 'MultiplierQuestion',
    type: `Play Begins and Ends`,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: `1st & GOAL`,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 49,
    componentName: 'MultiplierQuestion',
    type: `1ST & 4 AT NE 4       LIVE PLAY `,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 50,
    componentName: 'MultiplierQuestion',
    type: `LIVE PLAY`,
    playTitle: `Will Jaguars Score a TD?`,
    component: `A-B`,
    choices: ['No', 'Yes'],
    forTeam: { id: 1, teamName: `Patriots` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: `Yes`,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 51,
    componentName: 'MultiplierQuestion',
    type: `Multiplier 2X`,
    playTitle: `Will Jaguars Kick for Extra Point?`,
    component: `A-B`,
    choices: ['No', 'Yes'],
    forTeam: { id: 1, teamName: `Patriots` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: `Yes`,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 52,
    componentName: 'MultiplierQuestion',
    type: `Play in Progress + Results`,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 53,
    componentName: 'MultiplierQuestion',
    type: `Play Begins and Ends`,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: `TOUCHDOWN`,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 54,
    componentName: 'MultiplierQuestion',
    type: `1ST & 10 AT NE 15`,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 55,
    componentName: 'MultiplierQuestion',
    type: `LIVE PLAY`,
    playTitle: `Pass, Run or Turnover`,
    component: `3-Sided`,
    choices: [
      { id: 0, value: "'Run'" },
      { id: 1, value: "'Pass'" },
      { id: 2, value: "'or Turnover'" },
    ],
    forTeam: { id: 1, teamName: `Patriots` },
    title: null,
    shortHand: null,
    choiceType: 'MULTI',
    points: 50,
    tokens: 20,
    answer: `Pass`,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 56,
    componentName: 'MultiplierQuestion',
    type: `Multiplier 2X`,
    playTitle: `Loss, No Gain or Gain?`,
    component: `3-Sided`,
    choices: [
      { id: 0, value: "'Loss'" },
      { id: 1, value: "'No Gain'" },
      { id: 2, value: "'Gain'" },
    ],
    forTeam: { id: 1, teamName: `Patriots` },
    title: null,
    shortHand: null,
    choiceType: 'MULTI',
    points: 50,
    tokens: 20,
    answer: `Loss`,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 57,
    componentName: 'MultiplierQuestion',
    type: `Multiplier 3X`,
    playTitle: `# of Yards ?`,
    component: `Yard Selector`,
    choices: [
      { id: 0, value: "'0-3'" },
      { id: 1, value: "'4-10'" },
      { id: 2, value: "'11-15'" },
      { id: 3, value: "'16-25'" },
      { id: 4, value: "'26-35'" },
      { id: 5, value: "'+35'" },
    ],
    forTeam: { id: 1, teamName: `Patriots` },
    title: null,
    shortHand: null,
    choiceType: 'MULTI',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 58,
    componentName: 'MultiplierQuestion',
    type: `Play in Progress + Results`,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 59,
    componentName: 'MultiplierQuestion',
    type: `Play Begins and Ends`,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 60,
    componentName: 'MultiplierQuestion',
    type: null,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 61,
    componentName: 'MultiplierQuestion',
    type: `2ND & 13 AT NE 18`,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 62,
    componentName: 'MultiplierQuestion',
    type: `LIVE PLAY`,
    playTitle: `# of Yards ?`,
    component: `Yard Selector`,
    choices: [
      { id: 0, value: "'0-3'" },
      { id: 1, value: "'4-10'" },
      { id: 2, value: "'11-15'" },
      { id: 3, value: "'16-25'" },
      { id: 4, value: "'26-35'" },
      { id: 5, value: "'+35'" },
    ],
    forTeam: { id: 1, teamName: `Patriots` },
    title: null,
    shortHand: null,
    choiceType: 'MULTI',
    points: 50,
    tokens: 20,
    answer: `12 yards Gain`,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 63,
    componentName: 'MultiplierQuestion',
    type: `3RD & 1 AT NE 6`,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 64,
    componentName: 'MultiplierQuestion',
    type: `LIVE PLAY`,
    playTitle: `Loss, No Gain or Gain?`,
    component: `3-Sided`,
    choices: [
      { id: 0, value: "'Loss'" },
      { id: 1, value: "'No Gain'" },
      { id: 2, value: "'Gain'" },
    ],
    forTeam: { id: 1, teamName: `Patriots` },
    title: null,
    shortHand: null,
    choiceType: 'MULTI',
    points: 50,
    tokens: 20,
    answer: `Gain`,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 65,
    componentName: 'MultiplierQuestion',
    type: `Sponsor Play`,
    playTitle: `"Player to score first touchdown?`,
    component: `A-B`,
    choices: ['L Fournette', 'T. J. Yeldon'],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: `Sponsor`,
    shortHand: `Sponsor`,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: `L Fournette`,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 66,
    componentName: 'MultiplierQuestion',
    type: null,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 67,
    componentName: 'MultiplierQuestion',
    type: `1ST & 4 AT NE 4`,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 68,
    componentName: 'MultiplierQuestion',
    type: `LIVE PLAY`,
    playTitle: `Pass, Run or Turnover`,
    component: `3-Sided`,
    choices: [
      { id: 0, value: "'Run'" },
      { id: 1, value: "'Pass'" },
      { id: 2, value: "'or Turnover'" },
    ],
    forTeam: { id: 1, teamName: `Patriots` },
    title: null,
    shortHand: null,
    choiceType: 'MULTI',
    points: 50,
    tokens: 20,
    answer: `Run`,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 69,
    componentName: 'MultiplierQuestion',
    type: `Multiplier 2X`,
    playTitle: `Loss, No Gain or Gain?`,
    component: `3-Sided`,
    choices: [
      { id: 0, value: "'Loss'" },
      { id: 1, value: "'No Gain'" },
      { id: 2, value: "'Gain'" },
    ],
    forTeam: { id: 1, teamName: `Patriots` },
    title: null,
    shortHand: null,
    choiceType: 'MULTI',
    points: 50,
    tokens: 20,
    answer: `Gain`,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 70,
    componentName: 'MultiplierQuestion',
    type: `Multiplier 3X`,
    playTitle: `Will Jaguars score a TOUCHDOWN?`,
    component: `A-B`,
    choices: ['No', 'Yes'],
    forTeam: { id: 1, teamName: `Patriots` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: `Yes`,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 71,
    componentName: 'MultiplierQuestion',
    type: `Multiplier 4X`,
    playTitle: `Extra Point?`,
    component: `A-B`,
    choices: ['Good', 'No'],
    forTeam: { id: 1, teamName: `Patriots` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: `Good`,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 72,
    componentName: 'MultiplierQuestion',
    type: `Play in Progress + Results`,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 73,
    componentName: 'MultiplierQuestion',
    type: `1ST & 10 AT NE 40`,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 74,
    componentName: 'MultiplierQuestion',
    type: `GameMaster`,
    playTitle: `Will a Patriot be injured this quarter?`,
    component: `A-B`,
    choices: ['No', 'Yes'],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: `Prize Play`,
    shortHand: `Prize Play`,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: `Yes`,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 75,
    componentName: 'MultiplierQuestion',
    type: null,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 76,
    componentName: 'MultiplierQuestion',
    type: `1ST & 10 AT JAX 13`,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 77,
    componentName: 'MultiplierQuestion',
    type: `LIVE PLAY`,
    playTitle: `What will the next play be?`,
    component: `A-B`,
    choices: ['Run', 'Pass'],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: `Pass`,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 78,
    componentName: 'MultiplierQuestion',
    type: `Multiplier 2X`,
    playTitle: `Loss, No Gain or Gain?`,
    component: `3-Sided`,
    choices: [
      { id: 0, value: "'Loss'" },
      { id: 1, value: "'No Gain'" },
      { id: 2, value: "'Gain'" },
    ],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'MULTI',
    points: 50,
    tokens: 20,
    answer: `Gain`,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 79,
    componentName: 'MultiplierQuestion',
    type: `Multiplier 3X`,
    playTitle: `# of Yards ?`,
    component: `Yard Selector`,
    choices: [
      { id: 0, value: "'0-3'" },
      { id: 1, value: "'4-10'" },
      { id: 2, value: "'11-15'" },
      { id: 3, value: "'16-25'" },
      { id: 4, value: "'26-35'" },
      { id: 5, value: "'+35'" },
    ],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'MULTI',
    points: 50,
    tokens: 20,
    answer: `12 yards Gain`,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 80,
    componentName: 'MultiplierQuestion',
    type: `Play in Progress + Results`,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 81,
    componentName: 'MultiplierQuestion',
    type: `1ST & 1 AT JAX 1`,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 82,
    componentName: 'MultiplierQuestion',
    type: `LIVE PLAY`,
    playTitle: `Will Patriots score a TOUCHDOWN?`,
    component: `A-B`,
    choices: ['No', 'Yes'],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: `Yes`,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 83,
    componentName: 'MultiplierQuestion',
    type: `0:55`,
    playTitle: `Extra Point?`,
    component: `A-B`,
    choices: ['Good', 'No'],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: `Good`,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 84,
    componentName: 'MultiplierQuestion',
    type: `Half Time`,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 85,
    componentName: 'MultiplierQuestion',
    type: `Live Play`,
    playTitle: `Jaguars Receive the Ball`,
    component: `3Sided`,
    choices: [
      { id: 0, value: "'Out/Bounds'" },
      { id: 1, value: "'Touch Back'" },
      { id: 2, value: "'Return'" },
    ],
    forTeam: { id: 1, teamName: `Patriots` },
    title: `Receives`,
    shortHand: `Receives`,
    choiceType: 'MULTI',
    points: 50,
    tokens: 20,
    answer: `Touch Back`,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 86,
    componentName: 'MultiplierQuestion',
    type: null,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 87,
    componentName: 'MultiplierQuestion',
    type: null,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 88,
    componentName: 'MultiplierQuestion',
    type: null,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 89,
    componentName: 'MultiplierQuestion',
    type: null,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 90,
    componentName: 'MultiplierQuestion',
    type: `AD Play`,
    playTitle: `Coca-Cola Challenge`,
    component: `VIDEO`,
    choices: [
      'Pepsi Challenge -                                 watch this video before halftime and WIN 50 Tokens',
    ],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 91,
    componentName: 'MultiplierQuestion',
    type: null,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 92,
    componentName: 'MultiplierQuestion',
    type: null,
    playTitle: null,
    component: null,
    choices: [],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 93,
    componentName: 'MultiplierQuestion',
    type: `GameMaster`,
    playTitle: `What will the next play be?`,
    component: `A-B`,
    choices: ['Run', 'Pass'],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: `GameMaster`,
    shortHand: `GameMaster`,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: `Pass`,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 94,
    componentName: 'MultiplierQuestion',
    type: `Sponsor Play`,
    playTitle: `Player & Cameraman
Collide this half?`,
    component: `A-B`,
    choices: ['No', 'Yes'],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: `Sponsor`,
    shortHand: `Sponsor`,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: `Yes`,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 95,
    componentName: 'MultiplierQuestion',
    type: `AD Play`,
    playTitle: `Pepsi Challenge`,
    component: `VIDEO`,
    choices: [
      'Pepsi Challenge -                                 watch this video before halftime and WIN 50 Tokens and a Free Drink  at Halftime',
    ],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: null,
    shortHand: null,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: null,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
  {
    sequence: 96,
    componentName: 'MultiplierQuestion',
    type: `Prize Play`,
    playTitle: `Will Bengals pass
to A. J. Green this series?`,
    component: `A-B`,
    choices: ['No', 'Yes'],
    forTeam: { id: 2, teamName: `Jaguars` },
    title: `Prize Play`,
    shortHand: `Prize Play`,
    choiceType: 'AB',
    points: 50,
    tokens: 20,
    answer: `Yes`,
    labels: [{ sequence: 1, value: null }],
    length: NaN,
    specialTimer: NaN,
    note: null,
  },
]
