module.exports = [
  {
    id: 1000,
    nextId: 1001,
    componentName: 'ExplainationScreen',
    isQuestion: false,
    length: 15,
  },
  {
    id: 1001,
    nextId: 1002,
    componentName: 'GetReady',
    isQuestion: false,
    length: 15,
  },
  {
    id: 1002,
    nextId: 1003,
    componentName: 'Kickoff',
    isQuestion: false,
    length: 2,
  },

  {
    id: 1003,
    nextId: 1008,
    isQuestion: true,
    componentName: 'MultiplierQuestion',
    playTitle: 'Patriots Receive the Ball',
    choices: [
      { id: 0, value: 'Out/Bounds', nextId: 0 },
      { id: 1, value: 'Touchback', nextId: 0 },
      { id: 2, value: 'Return', nextId: 0 },
    ],
    correctAnswer: 'Touchback',
    forTeam: { id: 2, teamName: 'Patriots' },
    title: 'Receives',
    shortHand: 'Receives',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 3,
    inProgressLength: 3,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    hideTimeout: true,
    footage: '0:12',
    inProgressFootage: '0:16',
    type: 'LivePlay',
  },
  /*
  {
    id: 1004,
    nextId: 0,
    isQuestion: true,
    componentName: 'MultiplierQuestion',
    playTitle: 'The ball',
    choices: [
      { id: 0, value: 'kick ob', nextId: 0 },
      { id: 1, value: 'roll ob', nextId: 0 },
    ],
    correctAnswer: 'kick ob',
    forTeam: { id: 2, teamName: 'Patriots' },
    title: '',
    shortHand: 'The Ball',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 8,
    inProgressLength: 1,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    hideTimeout: true,
    footage: '0:12',
    inProgressFootage: '0:16',
    type: 'LivePlay',
  },
  {
    id: 1005,
    nextId: 0,
    isQuestion: true,
    componentName: 'MultiplierQuestion',
    playTitle: 'How - TB',
    choices: [
      { id: 0, value: 'kneel', nextId: 0 },
      { id: 1, value: 'end zone', nextId: 0 },
    ],
    correctAnswer: 'end zone',
    forTeam: { id: 2, teamName: 'Patriots' },
    title: '',
    shortHand: 'How - TB',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 8,
    inProgressLength: 1,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    hideTimeout: true,
    footage: '0:12',
    inProgressFootage: '0:16',
    type: 'LivePlay',
  },
  {
    id: 1006,
    nextId: 0,
    isQuestion: true,
    componentName: 'MultiplierQuestion',
    playTitle: 'Loss, No Gain or Gain?',
    choices: [
      { id: 0, value: 'Loss', nextId: 0 },
      { id: 1, value: 'No Gain', nextId: 0 },
      { id: 2, value: 'Gain', nextId: 1007 },
    ],
    correctAnswer: 'Loss',
    forTeam: { id: 2, teamName: 'Patriots' },
    title: '',
    shortHand: '',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 8,
    inProgressLength: 1,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    hideTimeout: true,
    footage: '0:12',
    inProgressFootage: '0:16',
    type: 'LivePlay',
  },
  {
    id: 1007,
    nextId: 0,
    isQuestion: true,
    componentName: 'MultiplierQuestion',
    playTitle: '# of Yards ?',
    choices: [
      { id: 0, value: '0-5', nextId: 0 },
      { id: 1, value: '5-15', nextId: 0 },
      { id: 2, value: '15-25', nextId: 0 },
      { id: 3, value: '25-35', nextId: 0 },
      { id: 4, value: '+35', nextId: 0 },
    ],
    correctAnswer: 'No Gain',
    forTeam: { id: 2, teamName: 'Patriots' },
    title: '',
    shortHand: '',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 8,
    inProgressLength: 1,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    hideTimeout: true,
    footage: '0:12',
    inProgressFootage: '0:16',
    type: 'LivePlay',
  },
*/
  //-------------------------------------------------------------------------
  {
    id: 1008,
    nextId: 1012,
    isQuestion: true,
    componentName: 'GameMasterQuestion',
    playTitle: 'What will the next play be?',
    choices: [
      { id: 0, value: 'Run', nextId: 0 },
      { id: 1, value: 'Pass', nextId: 0 },
    ],
    correctAnswer: 'Pass',
    forTeam: {},
    title: 'GameMaster',
    shortHand: 'GameMaster',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [{ sequence: 1, value: 'Play Card  - Action lasts 5 sec.' }],
    length: 3,
    specialTimer: 27,
    isMultiplier: false,
    backgroundColor: '#19d1bf',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    ringImage: 'symbol-gm_white.svg',
    //showResult: true,
    hideTimeout: true,
    stars: 1,
    footage: '0:29',
    inProgressFootage: '0:36',
    type: 'GameMaster',
  },
  //----------------------------------------------------------------------------------------------------------------------
  /*
  {
    id: 1009,
    nextId: 1012,
    isQuestion: true,
    componentName: 'MultiplierQuestion',
    playTitle: 'Loss, No Gain or Gain?',
    choices: [
      { id: 0, value: 'Loss', nextId: 0 },
      { id: 1, value: 'No Gain', nextId: 0 },
      { id: 2, value: 'Gain', nextId: 1011 },
    ],
    correctAnswer: 'Gain',
    forTeam: { id: 2, teamName: 'Patriots' },
    title: '',
    shortHand: '',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 4, //16,
    inProgressLength: 5,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    isTextCard: true,
    footage: '0:29',
    inProgressFootage: '0:36',
    type: 'LivePlay',
  },
  {
    id: 1011,
    nextId: 0,
    isQuestion: true,
    componentName: 'MultiplierQuestion',
    playTitle: '# of Yards ?',
    choices: [
      { id: 0, value: '0-5', nextId: 0 },
      { id: 1, value: '6-10', nextId: 0 },
      { id: 2, value: '11-20', nextId: 0 },
      { id: 3, value: '21-40', nextId: 0 },
      { id: 4, value: '+40', nextId: 0 },
    ],
    correctAnswer: 'No Gain',
    forTeam: { id: 2, teamName: 'Patriots' },
    title: '',
    shortHand: '',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 5,
    inProgressLength: 7,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    isTextCard: true,
    footage: '0:29',
    inProgressFootage: '0:36',
    type: 'LivePlay',
  },
*/
  //----------------------------------------------------------------------------------------------------------------------
  {
    id: 1012,
    nextId: 1015,
    isQuestion: true,
    componentName: 'MultiplierQuestion',
    playTitle: 'Run, Pass or Turnover',
    choices: [
      { id: 0, value: 'Run', nextId: 1013 },
      { id: 1, value: 'Pass', nextId: 1013 },
      { id: 2, value: 'Turnover', nextId: 0 },
    ],
    correctAnswer: 'Pass',
    forTeam: { id: 2, teamName: 'Patriots' },
    title: '',
    shortHand: '',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 8,
    inProgressLength: 6,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    isTextCard: true,
    hideTimeout: true,
    footage: '0:50',
    inProgressFootage: '0:57',
    type: 'LivePlay',
  },
  {
    id: 1013,
    nextId: 0,
    isQuestion: true,
    componentName: 'MultiplierQuestion',
    playTitle: 'Loss, No Gain, Gain',
    choices: [
      { id: 0, value: 'Loss', nextId: 0 },
      { id: 1, value: 'No Gain', nextId: 0 },
      { id: 2, value: 'Gain', nextId: 0 },
    ],
    correctAnswer: 'Gain',
    forTeam: { id: 2, teamName: 'Patriots' },
    title: '',
    shortHand: '',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 9,
    inProgressLength: 8,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    isTextCard: true,
    hideTimeout: true,
    footage: '0:50',
    inProgressFootage: '0:57',
    type: 'LivePlay',
  },
  /*
  {
    id: 1014,
    nextId: 0,
    isQuestion: true,
    componentName: 'MultiplierQuestion',
    playTitle: '# of Yards?',
    choices: [
      { id: 0, value: '0-3', nextId: 0 },
      { id: 1, value: '4-10', nextId: 0 },
      { id: 2, value: '11-15', nextId: 0 },
      { id: 3, value: '16-25', nextId: 0 },
      { id: 4, value: '+35', nextId: 0 },
    ],
    correctAnswer: '+35',
    forTeam: { id: 2, teamName: 'Patriots' },
    title: '',
    shortHand: '',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 3,
    inProgressLength: 8,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    isTextCard: true,
    footage: '0:50',
    inProgressFootage: '0:57',
    type: 'LivePlay',
  },
*/
  //----------------------------------------------------------------------------------------------------------------------

  {
    id: 1015,
    nextId: 1016,
    isQuestion: true,
    componentName: 'MultiplierQuestion',
    playTitle: 'Run, Pass or TO',
    choices: [
      { id: 0, value: 'Run', nextId: 10151 },
      { id: 1, value: 'Pass', nextId: 10151 },
      { id: 2, value: 'TO', nextId: 0 },
    ],
    correctAnswer: 'TO',
    forTeam: { id: 2, teamName: 'Patriots' },
    title: '',
    shortHand: '',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 28,
    inProgressLength: 3,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    hideTimeout: true,
    footage: '1:8',
    inProgressFootage: '1:8',
    type: 'LivePlay',
  },
  {
    id: 10151,
    nextId: 0,
    isQuestion: true,
    componentName: 'MultiplierQuestion',
    playTitle: 'Loss, No Gain, Gain',
    choices: [
      { id: 0, value: 'Loss', nextId: 0 },
      { id: 1, value: 'No Gain', nextId: 0 },
      { id: 2, value: 'Gain', nextId: 1014 },
    ],
    correctAnswer: 'Gain',
    forTeam: { id: 2, teamName: 'Patriots' },
    title: '',
    shortHand: '',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 9,
    inProgressLength: 8,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    hideTimeout: true,
    footage: '1:8',
    inProgressFootage: '1:8',
    type: 'LivePlay',
  },
  //----------------------------------------------------------------------------------------------------------------------
  {
    id: 1016,
    nextId: 1017,
    isQuestion: true,
    componentName: 'AdvertisementQuestion',
    playTitle: 'Will Tom Brady be intercepted this series?',
    choices: [
      { id: 0, value: 'No', nextId: 0 },
      { id: 1, value: 'Yes', nextId: 0 },
    ],
    correctAnswer: 'No',
    forTeam: {},
    title: 'Prize Play',
    shortHand: 'Prize Play',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [{ sequence: 1, value: 'Play Card  - Action lasts 5 sec.' }],
    length: 3,
    specialTimer: 27,
    isMultiplier: false,
    backgroundColor: '#9368AA',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    ringImage: 'symbol-prize_white.svg',
    prizeImage: 'prize-icon-coffee.jpg',
    prizeDesc: 'Free Coffee',
    prizeDetailDesc: 'Prize Play',
    prizePoints: 0,
    //showResult: true,
    hideTimeout: true,
    stars: 1,
    footage: '1:19',
    inProgressFootage: '1:19',
    type: 'Prize',
  },
  //------------------------------------------------------------------------------
  {
    id: 1017,
    nextId: 1020,
    isQuestion: true,
    componentName: 'MultiplierQuestion',
    playTitle: 'Run or Pass',
    choices: [
      { id: 0, value: 'Run', nextId: 1018 },
      { id: 1, value: 'Pass', nextId: 1018 },
    ],
    correctAnswer: 'Pass',
    forTeam: { id: 2, teamName: 'Patriots' },
    title: '',
    shortHand: '',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 14,
    inProgressLength: 10,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    hideTimeout: true,
    footage: '1:44',
    inProgressFootage: '1:48',
    type: 'LivePlay',
  },
  {
    id: 1018,
    nextId: 0,
    isQuestion: true,
    componentName: 'MultiplierQuestion',
    playTitle: 'Loss, No Gain, Gain',
    choices: [
      { id: 0, value: 'Loss', nextId: 0 },
      { id: 1, value: 'No Gain', nextId: 0 },
      { id: 2, value: 'Gain', nextId: 1019 },
    ],
    correctAnswer: 'Gain',
    forTeam: { id: 2, teamName: 'Patriots' },
    title: '',
    shortHand: '',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 14,
    inProgressLength: 10,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    hideTimeout: true,
    footage: '1:44',
    inProgressFootage: '1:48',
    type: 'LivePlay',
  },
  {
    id: 1019,
    nextId: 0,
    isQuestion: true,
    componentName: 'MultiplierQuestion',
    playTitle: '# of Yards?',
    choices: [
      { id: 0, value: '0-3', nextId: 0 },
      { id: 1, value: '4-10', nextId: 0 },
      { id: 2, value: '11-15', nextId: 0 },
      { id: 3, value: '16-25', nextId: 0 },
      { id: 4, value: 'TD', nextId: 0 },
    ],
    correctAnswer: '16-25',
    forTeam: { id: 2, teamName: 'Patriots' },
    title: '',
    shortHand: '',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 14,
    inProgressLength: 10,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    hideTimeout: true,
    footage: '1:44',
    inProgressFootage: '1:48',
    type: 'LivePlay',
  },
  //-----------------------------------------------------------------------
  {
    id: 1020,
    nextId: 2000,
    isQuestion: true,
    componentName: 'ExtraPointQuestion',
    playTitle: 'Will they make it?',
    choices: [
      { id: 0, value: 'No', nextId: 0 },
      { id: 1, value: 'Yes', nextId: 0 },
    ],
    correctAnswer: 'Yes',
    forTeam: { id: 2, teamName: 'Patriots' },
    title: 'Field Goal',
    shortHand: 'Field Goal',
    choiceType: 'MULTI',
    points: 3,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 3,
    inProgressLength: 2,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    hideTimeout: true,
    stars: 1,
    footage: '1:54',
    inProgressFootage: '1:57',
    type: 'ExtraPoint',
  },
  //--------------------------------------------------------------------------------------------------------------------
  {
    id: 2000,
    nextId: 2001,
    isQuestion: true,
    componentName: 'MultiplierQuestion',
    playTitle: '1st Down - Run, Pass, or Turnover',
    choices: [
      { id: 0, value: 'Run', nextId: 0 },
      { id: 1, value: 'Pass', nextId: 0 },
      { id: 2, value: 'Turnover', nextId: 0 },
    ],
    correctAnswer: 'Pass',
    forTeam: { id: 1, teamName: 'Jaguars' },
    title: '',
    shortHand: '',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 3,
    inProgressLength: 4,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    hideTimeout: true,
    footage: '2:15',
    inProgressFootage: '2:23',
    type: 'LivePlay',
  },

  {
    id: 2001,
    nextId: 2101,
    isQuestion: true,
    componentName: 'MultiplierQuestion',
    playTitle: '1st Down - Run, Pass, TD',
    choices: [
      { id: 0, value: 'Run', nextId: 0 },
      { id: 1, value: 'Pass', nextId: 0 },
      { id: 2, value: 'TD', nextId: 0 },
    ],
    correctAnswer: 'TD',
    forTeam: { id: 1, teamName: 'Jaguars' },
    title: '',
    shortHand: '',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 3,
    inProgressLength: 4,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    hideTimeout: true,
    footage: '2:32',
    inProgressFootage: '2:38',
    type: 'LivePlay',
  },

  {
    id: 2101,
    nextId: 2002,
    isQuestion: true,
    componentName: 'ExtraPointQuestion',
    playTitle: 'Will they make it?',
    choices: [
      { id: 0, value: 'No', nextId: 0 },
      { id: 1, value: 'Yes', nextId: 0 },
    ],
    correctAnswer: 'Yes',
    forTeam: { id: 2, teamName: 'Patriots' },
    title: 'Extra Point',
    shortHand: 'Extra Point',
    choiceType: 'MULTI',
    points: 1,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 3,
    inProgressLength: 2,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    hideTimeout: true,
    footage: '2:45',
    inProgressFootage: '2:47',
    type: 'ExtraPoint',
  },

  {
    id: 2002,
    nextId: 2003,
    isQuestion: true,
    componentName: 'SponsorQuestion',
    playTitle: 'Will the JAGS score this possession?',
    choices: [
      { id: 0, value: 'No', nextId: 0 },
      { id: 1, value: 'Yes', nextId: 0 },
    ],
    correctAnswer: 'Yes',
    forTeam: {},
    title: 'Sponsor Play',
    shortHand: 'Sponsor Play',
    choiceType: 'MULTI',
    points: 5000,
    tokens: 50,
    answer: 1,
    labels: [],
    length: 10,
    specialTimer: 27,
    isMultiplier: false,
    backgroundColor: '#495bdb',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    ringImage: 'symbol-sponsor_white.svg',
    showResult: true,
    stars: 1,
    footage: '3:2',
    inProgressFootage: '3:9',
    type: 'Sponsor',
  },

  {
    id: 2003,
    nextId: 2004,
    isQuestion: true,
    componentName: 'MultiplierQuestion',
    playTitle: 'Run or Pass',
    choices: [
      { id: 0, value: 'Run', nextId: 0 },
      { id: 1, value: 'Pass', nextId: 0 },
    ],
    correctAnswer: 'Run',
    forTeam: { id: 1, teamName: 'Jaguars' },
    title: '',
    shortHand: '',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 3,
    inProgressLength: 4,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    hideTimeout: true,
    footage: '3:17',
    inProgressFootage: '3:25',
    type: 'LivePlay',
  },
  //---------------------------------------------------------------------
  {
    id: 2004,
    nextId: 2006,
    isQuestion: true,
    componentName: 'MultiplierQuestion',
    playTitle: 'Loss, No Gain, Gain',
    choices: [
      { id: 0, value: 'Loss', nextId: 0 },
      { id: 1, value: 'No Gain', nextId: 0 },
      { id: 2, value: 'Gain', nextId: 2005 },
    ],
    correctAnswer: 'Gain',
    forTeam: { id: 1, teamName: 'Jaguars' },
    title: '',
    shortHand: '',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 3,
    inProgressLength: 4,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    hideTimeout: true,
    footage: '3:39',
    inProgressFootage: '3:43',
    type: 'LivePlay',
  },
  {
    id: 2005,
    nextId: 0,
    isQuestion: true,
    componentName: 'MultiplierQuestion',
    playTitle: '# of Yards?',
    choices: [
      { id: 0, value: '1', nextId: 0 },
      { id: 1, value: '2', nextId: 0 },
      { id: 2, value: '3', nextId: 0 },
      { id: 3, value: '4', nextId: 0 },
      { id: 4, value: 'TD', nextId: 0 },
    ],
    correctAnswer: '3',
    forTeam: { id: 1, teamName: 'Jaguars' },
    title: '',
    shortHand: '',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 3,
    inProgressLength: 8,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    hideTimeout: true,
    footage: '3:39',
    inProgressFootage: '3:43',
    type: 'LivePlay',
  },
  //-----------------------------------------------------------------------------------

  {
    id: 2006,
    nextId: 2007,
    isQuestion: true,
    componentName: 'ExtraPointQuestion',
    playTitle: 'Will they make it?',
    choices: [
      { id: 0, value: 'No', nextId: 0 },
      { id: 1, value: 'Yes', nextId: 0 },
    ],
    correctAnswer: 'Yes',
    forTeam: { id: 2, teamName: 'Patriots' },
    title: 'Extra Point',
    shortHand: 'Extra Point',
    choiceType: 'MULTI',
    points: 1,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 3,
    inProgressLength: 2,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    hideTimeout: true,
    footage: '3:52',
    inProgressFootage: '3:58',
    type: 'ExtraPoint',
  },
  //----------------------------------------------------------------------------------------------------------------------
  {
    id: 2007,
    nextId: 2008,
    isQuestion: true,
    componentName: 'GameMasterQuestion',
    playTitle: 'How does this play end?',
    choices: [
      { id: 0, value: 'Loss', nextId: 0 },
      { id: 1, value: 'Gain', nextId: 0 },
      { id: 2, value: 'Flag', nextId: 0 },
    ],
    correctAnswer: 'Flag',
    forTeam: {},
    title: 'GameMaster',
    shortHand: 'GameMaster',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [{ sequence: 1, value: 'Play Card  - Action lasts 5 sec.' }],
    length: 3,
    specialTimer: 27,
    isMultiplier: false,
    backgroundColor: '#19d1bf',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    ringImage: 'symbol-gm_white.svg',
    showResult: true,
    stars: 1,
    footage: '4:7',
    inProgressFootage: '4:16',
    type: 'GameMaster',
  },

  {
    id: 2008,
    nextId: 2009,
    isQuestion: true,
    componentName: 'MultiplierQuestion',
    playTitle: 'Patriots this play?',
    choices: [
      { id: 0, value: 'Loss', nextId: 0 },
      { id: 1, value: 'Gain', nextId: 0 },
      { id: 2, value: 'Touchdown', nextId: 0 },
    ],
    correctAnswer: 'Gain',
    forTeam: { id: 2, teamName: 'Patriots' },
    title: '',
    shortHand: '',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 3,
    inProgressLength: 8,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    hideTimeout: true,
    footage: '4:25',
    inProgressFootage: '4:31',
    type: 'LivePlay',
  },

  {
    id: 2009,
    nextId: 2010,
    isQuestion: true,
    componentName: 'AdvertisementQuestion',
    playTitle: 'Do the Patriots score this play?',
    choices: [
      { id: 0, value: 'No', nextId: 0 },
      { id: 1, value: 'Yes', nextId: 0 },
    ],
    correctAnswer: 'Yes',
    forTeam: {},
    title: 'Prize Play',
    shortHand: 'Prize Play',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [{ sequence: 1, value: 'Play Card  - Action lasts 5 sec.' }],
    length: 3,
    specialTimer: 27,
    isMultiplier: false,
    backgroundColor: '#9368AA',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    ringImage: 'symbol-prize_white.svg',
    prizeImage: 'prize-icon-coffee.jpg',
    prizeDesc: 'Free Coffee',
    prizeDetailDesc: 'Prize Play',
    prizePoints: 0,
    showResult: true,
    hideTimeout: true,
    stars: 1,
    footage: '4:39',
    inProgressFootage: '4:44',
    type: 'Prize',
  },

  //-------------------------------------------------------------------------------------------
  {
    id: 2010,
    nextId: 2015,
    isQuestion: true,
    componentName: 'MultiplierQuestion',
    playTitle: 'Jaguars Receive the Ball',
    choices: [
      { id: 0, value: 'Out/Bounds', nextId: 2011 },
      { id: 1, value: 'Touchback', nextId: 2012 },
      { id: 2, value: 'Return', nextId: 2013 },
    ],
    correctAnswer: 'Touchback',
    forTeam: { id: 1, teamName: 'Jaguars' },
    title: 'Receives',
    shortHand: 'Receives',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 3,
    inProgressLength: 3,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    hideTimeout: true,
    footage: '5:6',
    inProgressFootage: '5:10',
    type: 'LivePlay',
  },
  {
    id: 2011,
    nextId: 0,
    isQuestion: true,
    componentName: 'MultiplierQuestion',
    playTitle: 'The ball',
    choices: [
      { id: 0, value: 'kick ob', nextId: 0 },
      { id: 1, value: 'roll ob', nextId: 0 },
    ],
    correctAnswer: 'kick ob',
    forTeam: { id: 1, teamName: 'Jaguars' },
    title: '',
    shortHand: 'The Ball',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 8,
    inProgressLength: 1,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    hideTimeout: true,
    footage: '5:6',
    inProgressFootage: '5:10',
    type: 'LivePlay',
  },
  {
    id: 2012,
    nextId: 0,
    isQuestion: true,
    componentName: 'MultiplierQuestion',
    playTitle: 'How - TB',
    choices: [
      { id: 0, value: 'kneel', nextId: 0 },
      { id: 1, value: 'end zone', nextId: 0 },
    ],
    correctAnswer: 'end zone',
    forTeam: { id: 1, teamName: 'Jaguars' },
    title: '',
    shortHand: 'How - TB',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 8,
    inProgressLength: 1,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    hideTimeout: true,
    footage: '5:6',
    inProgressFootage: '5:10',
    type: 'LivePlay',
  },
  {
    id: 2013,
    nextId: 0,
    isQuestion: true,
    componentName: 'MultiplierQuestion',
    playTitle: 'Loss, No Gain or Gain?',
    choices: [
      { id: 0, value: 'Loss', nextId: 0 },
      { id: 1, value: 'No Gain', nextId: 0 },
      { id: 2, value: 'Gain', nextId: 2014 },
    ],
    correctAnswer: 'Loss',
    forTeam: { id: 1, teamName: 'Jaguars' },
    title: '',
    shortHand: '',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 8,
    inProgressLength: 1,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    hideTimeout: true,
    footage: '5:6',
    inProgressFootage: '5:10',
    type: 'LivePlay',
  },
  {
    id: 2014,
    nextId: 0,
    isQuestion: true,
    componentName: 'MultiplierQuestion',
    playTitle: '# of Yards?',
    choices: [
      { id: 0, value: '0-5', nextId: 0 },
      { id: 1, value: '5-15', nextId: 0 },
      { id: 2, value: '15-25', nextId: 0 },
      { id: 3, value: '25-35', nextId: 0 },
      { id: 4, value: '+35', nextId: 0 },
    ],
    correctAnswer: '25-35',
    forTeam: { id: 1, teamName: 'Jaguars' },
    title: '',
    shortHand: '',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 8,
    inProgressLength: 1,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    hideTimeout: true,
    footage: '5:6',
    inProgressFootage: '5:10',
    type: 'LivePlay',
  },

  //-------------------------------------------------------------------------------------------
  {
    id: 2015,
    nextId: 2016,
    isQuestion: true,
    componentName: 'SponsorQuestion',
    playTitle: 'Will the JAGS score this series?',
    choices: [
      { id: 0, value: 'No', nextId: 0 },
      { id: 1, value: 'Yes', nextId: 0 },
    ],
    correctAnswer: 'Yes',
    forTeam: {},
    title: 'Sponsor Play',
    shortHand: 'Sponsor Play',
    choiceType: 'MULTI',
    points: 5000,
    tokens: 50,
    answer: 1,
    labels: [],
    length: 10,
    specialTimer: 27,
    isMultiplier: false,
    backgroundColor: '#495bdb',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    ringImage: 'symbol-sponsor_white.svg',
    showResult: true,
    hideTimeout: true,
    stars: 1,
    footage: '5:27',
    inProgressFootage: '5:30',
    type: 'Sponsor',
  },
  //-------------------------------------------------------------------------------------------
  {
    id: 2016,
    nextId: 2017,
    isQuestion: true,
    componentName: 'MultiplierQuestion',
    playTitle: 'Loss, No Gain or Gain?',
    choices: [
      { id: 0, value: 'Loss', nextId: 0 },
      { id: 1, value: 'No Gain', nextId: 0 },
      { id: 2, value: 'Gain', nextId: 0 },
    ],
    correctAnswer: 'Gain',
    forTeam: { id: 1, teamName: 'Jaguars' },
    title: '',
    shortHand: '',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 8,
    inProgressLength: 1,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    hideTimeout: true,
    footage: '5:46',
    inProgressFootage: '5:50',
    type: 'LivePlay',
  },
  //-------------------------------------------------------------------------------------------
  {
    id: 2017,
    nextId: 2018,
    isQuestion: true,
    componentName: 'ExtraPointQuestion',
    playTitle: 'Will they make it?',
    choices: [
      { id: 0, value: 'No', nextId: 0 },
      { id: 1, value: 'Yes', nextId: 0 },
    ],
    correctAnswer: 'Yes',
    forTeam: { id: 2, teamName: 'Patriots' },
    title: 'Field Goal',
    shortHand: 'Field Goal',
    choiceType: 'MULTI',
    points: 3,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 3,
    inProgressLength: 2,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    hideTimeout: true,
    footage: '6:2',
    inProgressFootage: '6:7',
    type: 'ExtraPoint',
  },
  //-------------------------------------------------------------------------------------------
  {
    id: 2018,
    nextId: 2019,
    isQuestion: true,
    componentName: 'GameMasterQuestion',
    playTitle: 'Run, Pass, Flag',
    choices: [
      { id: 0, value: 'Run', nextId: 0 },
      { id: 1, value: 'Pass', nextId: 0 },
      { id: 2, value: 'Flag', nextId: 0 },
    ],
    correctAnswer: 'Run',
    forTeam: {},
    title: 'GameMaster',
    shortHand: 'GameMaster',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [{ sequence: 1, value: 'Play Card  - Action lasts 5 sec.' }],
    length: 3,
    specialTimer: 27,
    isMultiplier: false,
    backgroundColor: '#19d1bf',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    ringImage: 'symbol-gm_white.svg',
    showResult: true,
    hideTimeout: true,
    footage: '6:14',
    inProgressFootage: '6:23',
    type: 'GameMaster',
  },
  //-------------------------------------------------------------------------------------------
  {
    id: 2019,
    nextId: 2020,
    isQuestion: true,
    componentName: 'ExtraPointQuestion',
    playTitle: 'Will they make it?',
    choices: [
      { id: 0, value: 'No', nextId: 0 },
      { id: 1, value: 'Yes', nextId: 0 },
    ],
    correctAnswer: 'Run',
    forTeam: { id: 2, teamName: 'Patriots' },
    title: 'Field Goal',
    shortHand: 'Field Goal',
    choiceType: 'MULTI',
    points: 3,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 3,
    inProgressLength: 2,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    hideTimeout: true,
    footage: '6:38',
    inProgressFootage: '6:42',
    type: 'ExtraPoint',
  },
  //-------------------------------------------------------------------------------------------
  {
    id: 2020,
    nextId: 2021,
    isQuestion: true,
    componentName: 'AdvertisementQuestion',
    playTitle: 'Do the Patriots score this play?',
    choices: [
      { id: 0, value: 'No', nextId: 0 },
      { id: 1, value: 'Yes', nextId: 0 },
    ],
    correctAnswer: 'Yes',
    forTeam: {},
    title: 'Prize Play',
    shortHand: 'Prize Play',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [{ sequence: 1, value: 'Play Card  - Action lasts 5 sec.' }],
    length: 3,
    specialTimer: 27,
    isMultiplier: false,
    backgroundColor: '#9368AA',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    ringImage: 'symbol-prize_white.svg',
    prizeImage: 'prize-icon-coffee.jpg',
    prizeDesc: 'Free Coffee',
    prizeDetailDesc: 'Prize Play',
    prizePoints: 0,
    showResult: true,
    hideTimeout: true,
    stars: 1,
    footage: '6:48',
    inProgressFootage: '6:54',
    type: 'Prize',
  },
  //-------------------------------------------------------------------------------------------
  {
    id: 2021,
    nextId: 2022,
    isQuestion: true,
    componentName: 'MultiplierQuestion',
    playTitle: 'Gain, No Gain, TD',
    choices: [
      { id: 0, value: 'Gain', nextId: 0 },
      { id: 1, value: 'No Gain', nextId: 0 },
      { id: 2, value: 'Touchdown', nextId: 0 },
    ],
    correctAnswer: 'Touchdown',
    forTeam: { id: 2, teamName: 'Patriots' },
    title: '',
    shortHand: '',
    choiceType: 'MULTI',
    points: 0,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 8,
    inProgressLength: 1,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    hideTimeout: true,
    footage: '7:4',
    inProgressFootage: '7:14',
    type: 'LivePlay',
  },
  //-------------------------------------------------------------------------------------------
  {
    id: 2022,
    nextId: 9999,
    isQuestion: true,
    componentName: 'ExtraPointQuestion',
    playTitle: 'Will they make it?',
    choices: [
      { id: 0, value: 'No', nextId: 0 },
      { id: 1, value: 'Yes', nextId: 0 },
    ],
    correctAnswer: 'Yes',
    forTeam: { id: 2, teamName: 'Patriots' },
    title: 'Extra Point',
    shortHand: 'Extra Point',
    choiceType: 'MULTI',
    points: 1,
    tokens: 0,
    answer: 1,
    labels: [],
    length: 3,
    inProgressLength: 2,
    specialTimer: 13,
    isMultiplier: true,
    backgroundColor: '#c61818',
    backgroundImage: 'playalong-kickoff.jpg',
    ringColor: '#000000',
    hideTimeout: true,
    footage: '7:19',
    inProgressFootage: '7:24',
    type: 'ExtraPoint',
  },
  //--------------------------------------------------------------------------------------------------------------------
  {
    id: 9999,
    nextId: 0,
    componentName: 'Summary',
    title: 'Summary',
    shortHand: 'Summary',
  },
]
