const scriptExtension = {
  sequence: 15,
  isQuestion: false,
  componentName: 'PlayInProgress',
  length: 8,
  specialTimer: 13,
  next: {
    isQuestion: false,
    length: 3,
    componentName: 'GameMasterPlay',
    next: {
      sequence: 18,
      isQuestion: true,
      componentName: 'GameMasterQuestion',
      playTitle: `What will the next play be?`,
      choices: ['Run', 'Pass'],
      forTeam: { id: 1, teamName: `Patriots` },
      title: `GameMaster`,
      shortHand: `GameMaster`,
      choiceType: 'AB',
      points: 50,
      tokens: 20,
      answer: 1,
      labels: [{ sequence: 1, value: `Play Card  - Action lasts 5 sec.` }],
      length: 5,
      specialTimer: 27,
      note: null,
    },
  },
}

module.exports = {
  componentName: 'GetReady',
  isQuestion: false,
  length: 20,
  next: {
    componentName: 'ExplainationScreen',
    isQuestion: false,
    length: 4,
    next: {
      isQuestion: true,
      sequence: 10,
      componentName: 'MultiplierQuestion',
      playTitle: 'Patriots Receive the Ball via',
      choices: [
        { id: 0, value: 'Out/Bounds' },
        { id: 1, value: 'Touch Back' },
        { id: 2, value: 'Return' },
      ],
      forTeam: { id: 1, teamName: 'Patriots' },
      title: 'Receives',
      shortHand: 'Receives',
      choiceType: 'MULTI',
      points: 50,
      tokens: 20,
      answer: 1,
      labels: [],
      length: 8,
      specialTimer: 13,
      isMultiplier: true,
      next: {
        sequence: 11,
        isQuestion: true,
        componentName: 'MultiplierQuestion',
        playTitle: 'Loss, No Gain or Gain?',
        choices: [
          { id: 0, value: 'Loss' },
          { id: 1, value: 'No Gain' },
          { id: 2, value: 'Gain' },
        ],
        forTeam: { id: 1, teamName: 'Patriots' },
        title: 'Play Type',
        shortHand: 'Play Type',
        choiceType: 'MULTI',
        points: 50,
        tokens: 20,
        answer: null,
        labels: [],
        length: 8,
        specialTimer: 13,
        note: null,
        isMultiplier: true,
        next: [
          {
            sequence: 12,
            isQuestion: true,
            componentName: 'MultiplierQuestion',
            playTitle: `How - TB`,
            choices: ['Kneel', 'End Zone'],
            forTeam: { id: 1, teamName: 'Patriots' },
            title: null,
            shortHand: 'Touch back',
            choiceType: 'AB',
            points: 50,
            tokens: 20,
            answer: 2,
            labels: [],
            length: 8,
            specialTimer: 13,
            note: null,
            isMultiplier: true,
            next: scriptExtension,
          },
          {
            sequence: 13,
            isQuestion: true,
            componentName: 'MultiplierQuestion',
            playTitle: `The Ball`,
            choices: ['Kick OB', 'Rolls OB'],
            forTeam: { id: 1, teamName: 'Patriots' },
            title: null,
            shortHand: null,
            choiceType: 'AB',
            points: 50,
            tokens: 20,
            answer: null,
            labels: [],
            length: 8,
            specialTimer: 13,
            note: null,
            isMultiplier: true,
            next: scriptExtension,
          },
          {
            sequence: 14,
            isQuestion: true,
            componentName: 'MultiplierQuestion',
            playTitle: `# of Yards ?`,
            choices: [
              { id: 0, value: '0-3' },
              { id: 1, value: '4-10' },
              { id: 2, value: '11-15' },
              { id: 3, value: '16-25' },
              { id: 4, value: '26-35' },
              { id: 5, value: '+35' },
            ],
            forTeam: { id: 1, teamName: `Patriots` },
            title: 'Yards',
            shortHand: 'Yards',
            choiceType: 'MULTI',
            points: 50,
            tokens: 20,
            answer: null,
            labels: [],
            length: 8,
            specialTimer: 13,
            note: `LOCKOUT - 3 sec.  before the kick`,
            isMultiplier: true,
            next: scriptExtension,
          },
        ],
      },
    },
  },
}
